<div>
	<div>
		<div>Username</div>
		<div><input id="obj_txt_username" type="text" value="parto"></div>
	</div>
	<div>
		<div>Password</div>
		<div><input id="obj_txt_password" type="password" value="widjojo"></div>
	</div>
	<div style="margin-top: 10px">
		<button id="btn_login">Login</button>
	</div>
	
	<div id="txt_error" class="login-error-message hidden"></div>
	<div id="txt_result" class="login-result-message hidden"></div>

</div>