version: '3.9'

services:
  fgta5_webservice:
    container_name: fgta5_webservice
    image: webserver_8_2
    hostname: fgta5_webservice
    ports:
      - 8005:80
    networks:
      - devnetwork 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=true
    volumes:
      - ./../:/var/www/html:consistent
    working_dir: /var/www/html
   

networks:
  devnetwork:
    name: devnetwork
    external: true




